# Generated by Django 2.1.1 on 2018-10-17 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pa.Offer'),
        ),
    ]
