# Generated by Django 2.1.1 on 2018-10-17 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pa', '0002_auto_20181017_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pa.Offer'),
        ),
    ]
